# Generated by Django 5.1.4 on 2024-12-21 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=20)),
                ('secondary_phone', models.IntegerField(max_length=14)),
                ('seconday_email', models.EmailField(max_length=254)),
                ('present_address', models.TextField(max_length=100)),
                ('permanent_address', models.TextField(max_length=100)),
                ('profile_picture', models.FileField(upload_to='document/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
