# Generated by Django 5.1.4 on 2024-12-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='permanent_address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='present_address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='secondary_phone',
            field=models.IntegerField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='seconday_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
