# Generated by Django 5.1.4 on 2024-12-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_userinfo_bio_alter_userinfo_permanent_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='secondary_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
