# Generated by Django 5.1.2 on 2024-10-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdms_app', '0002_author_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='last_name',
            new_name='description',
        ),
    ]
