# Generated by Django 5.1.2 on 2024-10-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdms_app', '0003_rename_last_name_books_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='updated_at',
            new_name='due_date',
        ),
    ]
