# Generated by Django 5.1.2 on 2024-10-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdms_app', '0004_rename_updated_at_todo_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myauthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('myauthor', models.ManyToManyField(related_name='myauthor', to='rdms_app.myauthor')),
            ],
        ),
    ]
