# Generated by Django 5.1.4 on 2025-01-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_alter_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
