# Generated by Django 5.1.4 on 2025-01-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_comment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
    ]
